-- 008_create_employees_table.sql
-- Creates a table to store employee data for asset assignment purposes.
-- This table is NOT linked to auth.users and these are not login-capable users.

CREATE TABLE public.employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT UNIQUE,
  employee_number TEXT UNIQUE,
  department_id BIGINT REFERENCES public.departments(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;

-- Policies for employees table
-- Allow any authenticated user to view all employees (as they are needed for assignment dropdowns)
CREATE POLICY "Allow authenticated users to read employees"
ON public.employees
FOR SELECT
TO authenticated
USING (true);

-- Allow admins and IT staff to manage employees
CREATE POLICY "Allow admin/it_staff to manage employees"
ON public.employees
FOR ALL -- Includes INSERT, UPDATE, DELETE
TO authenticated
USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'it_staff')
)
WITH CHECK (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'it_staff')
);
