-- 009_create_suppliers_table.sql
-- Creates the suppliers table and its RLS policies.

CREATE TABLE public.suppliers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name TEXT NOT NULL,
  contact_person TEXT,
  email TEXT,
  phone TEXT,
  status TEXT DEFAULT 'pending' NOT NULL, -- e.g., active, pending, inactive
  category TEXT,
  rating NUMERIC(2, 1),
  contract_start DATE,
  contract_end DATE,
  address TEXT,
  website TEXT,
  tax_id TEXT,
  payment_terms TEXT,
  preferred_vendor BOOLEAN DEFAULT false,
  notes TEXT,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;

-- Policies for suppliers table

-- Allow any authenticated user to view all suppliers
-- Suppliers are generally not considered sensitive information in this context
CREATE POLICY "Allow authenticated users to read suppliers"
ON public.suppliers
FOR SELECT
TO authenticated
USING (true);

-- Allow admins and IT staff to manage suppliers (create, update, delete)
CREATE POLICY "Allow admin/it_staff to manage suppliers"
ON public.suppliers
FOR ALL -- Includes INSERT, UPDATE, DELETE
TO authenticated
USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'it_staff')
)
WITH CHECK (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'it_staff')
);
