-- 013_create_departments_table.sql
-- Creates the departments table and its RLS policies.

CREATE TABLE public.departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;

-- Policies for departments table

-- Allow any authenticated user to view all departments
CREATE POLICY "Allow authenticated users to read departments"
ON public.departments
FOR SELECT
TO authenticated
USING (true);

-- Allow admins and IT staff to manage departments (create, update, delete)
CREATE POLICY "Allow admin/it_staff to manage departments"
ON public.departments
FOR ALL -- Includes INSERT, UPDATE, DELETE
TO authenticated
USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'it_staff')
)
WITH CHECK (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'it_staff')
);
