create table
  public.draft_assets (
    id bigint primary key generated by default as identity,
    created_at timestamp with time zone not null default now(),
    product_name text,
    category text,
    serial_number text,
    model text,
    purchase_date date,
    purchase_price numeric,
    warranty_months integer,
    supplier_id bigint,
    image_url text,
    lifespan_years integer,
    current_department_id bigint,
    user_id uuid references auth.users (id)
  );

alter table public.draft_assets enable row level security;

create policy "Users can manage their own drafts" on public.draft_assets for all
to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
