drop extension if exists "pg_net";


  create table "public"."assets" (
    "id" uuid not null default gen_random_uuid(),
    "asset_tag" text not null,
    "serial_number" text not null,
    "product_name" text not null,
    "category" text,
    "purchase_date" date,
    "purchase_price" numeric,
    "current_department_id" bigint not null,
    "status" text not null default 'In Use'::text,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "supplier_id" bigint,
    "warranty_months" integer default 0,
    "image_url" text,
    "assigned_to_employee_id" bigint
      );



  create table "public"."departments" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "created_at" timestamp with time zone default now()
      );



  create table "public"."employees" (
    "id" bigint generated by default as identity not null,
    "full_name" text not null,
    "email" text,
    "employee_number" text,
    "department_id" bigint,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."employees" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "full_name" text,
    "department_id" bigint not null,
    "role" text not null,
    "created_at" timestamp with time zone default now(),
    "email" text
      );


alter table "public"."profiles" enable row level security;


  create table "public"."suppliers" (
    "id" bigint generated by default as identity not null,
    "company_name" text not null,
    "contact_person" text,
    "email" text,
    "phone" text,
    "address" text,
    "website" text,
    "tax_id" text,
    "payment_terms" text,
    "contract_start" date,
    "contract_end" date,
    "status" text not null default 'pending'::text,
    "rating" numeric(2,1),
    "preferred_vendor" boolean default false,
    "notes" text,
    "image_url" text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."suppliers" enable row level security;

CREATE UNIQUE INDEX assets_asset_tag_key ON public.assets USING btree (asset_tag);

CREATE UNIQUE INDEX assets_pkey ON public.assets USING btree (id);

CREATE UNIQUE INDEX assets_serial_number_key ON public.assets USING btree (serial_number);

CREATE UNIQUE INDEX departments_name_key ON public.departments USING btree (name);

CREATE UNIQUE INDEX departments_pkey ON public.departments USING btree (id);

CREATE UNIQUE INDEX employees_email_key ON public.employees USING btree (email);

CREATE UNIQUE INDEX employees_employee_number_key ON public.employees USING btree (employee_number);

CREATE UNIQUE INDEX employees_pkey ON public.employees USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX suppliers_pkey ON public.suppliers USING btree (id);

alter table "public"."assets" add constraint "assets_pkey" PRIMARY KEY using index "assets_pkey";

alter table "public"."departments" add constraint "departments_pkey" PRIMARY KEY using index "departments_pkey";

alter table "public"."employees" add constraint "employees_pkey" PRIMARY KEY using index "employees_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."suppliers" add constraint "suppliers_pkey" PRIMARY KEY using index "suppliers_pkey";

alter table "public"."assets" add constraint "assets_asset_tag_key" UNIQUE using index "assets_asset_tag_key";

alter table "public"."assets" add constraint "assets_assigned_to_employee_id_fkey" FOREIGN KEY (assigned_to_employee_id) REFERENCES public.employees(id) not valid;

alter table "public"."assets" validate constraint "assets_assigned_to_employee_id_fkey";

alter table "public"."assets" add constraint "assets_current_department_id_fkey" FOREIGN KEY (current_department_id) REFERENCES public.departments(id) not valid;

alter table "public"."assets" validate constraint "assets_current_department_id_fkey";

alter table "public"."assets" add constraint "assets_serial_number_key" UNIQUE using index "assets_serial_number_key";

alter table "public"."departments" add constraint "departments_name_key" UNIQUE using index "departments_name_key";

alter table "public"."employees" add constraint "employees_department_id_fkey" FOREIGN KEY (department_id) REFERENCES public.departments(id) not valid;

alter table "public"."employees" validate constraint "employees_department_id_fkey";

alter table "public"."employees" add constraint "employees_email_key" UNIQUE using index "employees_email_key";

alter table "public"."employees" add constraint "employees_employee_number_key" UNIQUE using index "employees_employee_number_key";

alter table "public"."profiles" add constraint "profiles_department_id_fkey" FOREIGN KEY (department_id) REFERENCES public.departments(id) not valid;

alter table "public"."profiles" validate constraint "profiles_department_id_fkey";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "profiles_role_check" CHECK ((role = ANY (ARRAY['system_admin'::text, 'it_staff'::text, 'department_pic'::text]))) not valid;

alter table "public"."profiles" validate constraint "profiles_role_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.delete_user_by_admin(user_id_to_delete uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  -- Security Check: The person executing this MUST be a 'system_admin'
  IF NOT EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid() AND role = 'system_admin'
  ) THEN
    RAISE EXCEPTION 'Access Denied: Only System Admins can delete users.';
  END IF;

  -- 1. Delete the user's Profile (Application Data)
  DELETE FROM public.profiles WHERE id = user_id_to_delete;

  -- 2. Delete the user's Auth Account (Login Credentials)
  -- Direct deletion from auth.users requires this specific SQL command
  DELETE FROM auth.users WHERE id = user_id_to_delete;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO public.profiles (id, full_name, role, department_id)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data ->> 'full_name', 'New User'),
    'it_staff', -- Default role is IT Staff (Safest default)
    (SELECT id FROM departments LIMIT 1) -- Assign to first available department
  );
  RETURN new;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
END;
$function$
;

grant delete on table "public"."assets" to "anon";

grant insert on table "public"."assets" to "anon";

grant references on table "public"."assets" to "anon";

grant select on table "public"."assets" to "anon";

grant trigger on table "public"."assets" to "anon";

grant truncate on table "public"."assets" to "anon";

grant update on table "public"."assets" to "anon";

grant delete on table "public"."assets" to "authenticated";

grant insert on table "public"."assets" to "authenticated";

grant references on table "public"."assets" to "authenticated";

grant select on table "public"."assets" to "authenticated";

grant trigger on table "public"."assets" to "authenticated";

grant truncate on table "public"."assets" to "authenticated";

grant update on table "public"."assets" to "authenticated";

grant delete on table "public"."assets" to "service_role";

grant insert on table "public"."assets" to "service_role";

grant references on table "public"."assets" to "service_role";

grant select on table "public"."assets" to "service_role";

grant trigger on table "public"."assets" to "service_role";

grant truncate on table "public"."assets" to "service_role";

grant update on table "public"."assets" to "service_role";

grant delete on table "public"."departments" to "anon";

grant insert on table "public"."departments" to "anon";

grant references on table "public"."departments" to "anon";

grant select on table "public"."departments" to "anon";

grant trigger on table "public"."departments" to "anon";

grant truncate on table "public"."departments" to "anon";

grant update on table "public"."departments" to "anon";

grant delete on table "public"."departments" to "authenticated";

grant insert on table "public"."departments" to "authenticated";

grant references on table "public"."departments" to "authenticated";

grant select on table "public"."departments" to "authenticated";

grant trigger on table "public"."departments" to "authenticated";

grant truncate on table "public"."departments" to "authenticated";

grant update on table "public"."departments" to "authenticated";

grant delete on table "public"."departments" to "service_role";

grant insert on table "public"."departments" to "service_role";

grant references on table "public"."departments" to "service_role";

grant select on table "public"."departments" to "service_role";

grant trigger on table "public"."departments" to "service_role";

grant truncate on table "public"."departments" to "service_role";

grant update on table "public"."departments" to "service_role";

grant delete on table "public"."employees" to "anon";

grant insert on table "public"."employees" to "anon";

grant references on table "public"."employees" to "anon";

grant select on table "public"."employees" to "anon";

grant trigger on table "public"."employees" to "anon";

grant truncate on table "public"."employees" to "anon";

grant update on table "public"."employees" to "anon";

grant delete on table "public"."employees" to "authenticated";

grant insert on table "public"."employees" to "authenticated";

grant references on table "public"."employees" to "authenticated";

grant select on table "public"."employees" to "authenticated";

grant trigger on table "public"."employees" to "authenticated";

grant truncate on table "public"."employees" to "authenticated";

grant update on table "public"."employees" to "authenticated";

grant delete on table "public"."employees" to "service_role";

grant insert on table "public"."employees" to "service_role";

grant references on table "public"."employees" to "service_role";

grant select on table "public"."employees" to "service_role";

grant trigger on table "public"."employees" to "service_role";

grant truncate on table "public"."employees" to "service_role";

grant update on table "public"."employees" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."suppliers" to "anon";

grant insert on table "public"."suppliers" to "anon";

grant references on table "public"."suppliers" to "anon";

grant select on table "public"."suppliers" to "anon";

grant trigger on table "public"."suppliers" to "anon";

grant truncate on table "public"."suppliers" to "anon";

grant update on table "public"."suppliers" to "anon";

grant delete on table "public"."suppliers" to "authenticated";

grant insert on table "public"."suppliers" to "authenticated";

grant references on table "public"."suppliers" to "authenticated";

grant select on table "public"."suppliers" to "authenticated";

grant trigger on table "public"."suppliers" to "authenticated";

grant truncate on table "public"."suppliers" to "authenticated";

grant update on table "public"."suppliers" to "authenticated";

grant delete on table "public"."suppliers" to "service_role";

grant insert on table "public"."suppliers" to "service_role";

grant references on table "public"."suppliers" to "service_role";

grant select on table "public"."suppliers" to "service_role";

grant trigger on table "public"."suppliers" to "service_role";

grant truncate on table "public"."suppliers" to "service_role";

grant update on table "public"."suppliers" to "service_role";


  create policy "Admin and IT Staff: Full Asset CUD Access"
  on "public"."assets"
  as permissive
  for all
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = ANY (ARRAY['system_admin'::text, 'it_staff'::text]))))));



  create policy "Admin and IT Staff: Full Asset Visibility"
  on "public"."assets"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = ANY (ARRAY['system_admin'::text, 'it_staff'::text]))))));



  create policy "Department PIC: Restrict Asset View to Department"
  on "public"."assets"
  as permissive
  for select
  to authenticated
using ((current_department_id = ( SELECT profiles.department_id
   FROM public.profiles
  WHERE (profiles.id = auth.uid()))));



  create policy "Allow admin/it_staff to manage employees"
  on "public"."employees"
  as permissive
  for all
  to authenticated
using ((( SELECT profiles.role
   FROM public.profiles
  WHERE (profiles.id = auth.uid())) = ANY (ARRAY['system_admin'::text, 'it_staff'::text])))
with check ((( SELECT profiles.role
   FROM public.profiles
  WHERE (profiles.id = auth.uid())) = ANY (ARRAY['system_admin'::text, 'it_staff'::text])));



  create policy "Allow authenticated users to read employees"
  on "public"."employees"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Admins can delete profiles"
  on "public"."profiles"
  as permissive
  for delete
  to public
using (public.is_admin());



  create policy "Admins can insert profiles"
  on "public"."profiles"
  as permissive
  for insert
  to public
with check (public.is_admin());



  create policy "Only System Admin can insert profiles"
  on "public"."profiles"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM public.profiles profiles_1
  WHERE ((profiles_1.id = auth.uid()) AND (profiles_1.role = 'system_admin'::text)))));



  create policy "Only System Admin can update any profile"
  on "public"."profiles"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.profiles profiles_1
  WHERE ((profiles_1.id = auth.uid()) AND (profiles_1.role = 'system_admin'::text)))));



  create policy "Users can update own profile"
  on "public"."profiles"
  as permissive
  for update
  to public
using (((auth.uid() = id) OR public.is_admin()));



  create policy "Users can update their own non-critical profile fields"
  on "public"."profiles"
  as permissive
  for update
  to authenticated
using ((auth.uid() = id));



  create policy "Users can view own profile"
  on "public"."profiles"
  as permissive
  for select
  to public
using (((auth.uid() = id) OR public.is_admin()));



  create policy "Allow authenticated users to read suppliers"
  on "public"."suppliers"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Allow system_admin/it_staff to manage suppliers"
  on "public"."suppliers"
  as permissive
  for all
  to authenticated
using ((( SELECT profiles.role
   FROM public.profiles
  WHERE (profiles.id = auth.uid())) = ANY (ARRAY['system_admin'::text, 'it_staff'::text])))
with check ((( SELECT profiles.role
   FROM public.profiles
  WHERE (profiles.id = auth.uid())) = ANY (ARRAY['system_admin'::text, 'it_staff'::text])));


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


  create policy "Allow authenticated doc uploads"
  on "storage"."objects"
  as permissive
  for all
  to public
using (((bucket_id = 'asset-docs'::text) AND (auth.role() = 'authenticated'::text)))
with check (((bucket_id = 'asset-docs'::text) AND (auth.role() = 'authenticated'::text)));



  create policy "Allow authenticated uploads"
  on "storage"."objects"
  as permissive
  for all
  to public
using (((bucket_id = 'asset-images'::text) AND (auth.role() = 'authenticated'::text)))
with check (((bucket_id = 'asset-images'::text) AND (auth.role() = 'authenticated'::text)));



  create policy "Allow authenticated users to upload images"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'Asset_image'::text));



  create policy "Allow authenticated users to view images"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using ((bucket_id = 'Asset_image'::text));



  create policy "Allow public doc viewing"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'asset-docs'::text));



  create policy "Allow public viewing"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'asset-images'::text));



